name: Continuous Integration - Flutter UI

on:
  pull_request:
    paths:
      - ui/**
  push:
    paths:
      - ui/**

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5

      - run: flutter pub get
        working-directory: ui/sprig_ui

      - name: Build MacOS
        if: runner.os == 'macOS'
        working-directory: ui/sprig_ui
        run: flutter build macos

      - name: Build Linux
        if: runner.os == 'linux'
        working-directory: ui/sprig_ui
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux

      # TODO: Build on Windows
