name: Continuous Integration

on:
  pull_request:
  push:


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v3
      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@main
      # Enable Actions caching for our local Nix builds
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and lint the project
        run: nix develop --command 'just'
