name: Continuous Integration

on:
  pull_request:
  push:


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v3
      # Install Nix
      - uses: DeterminateSystems/nix-installer-action@main
      # Enable Actions caching for our local Nix builds
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # Enable devenv's cache as well
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      # FIXME: Add a Nix flake to avoid having to install via nix profile
      - run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

    # - name: Run a single command in the devenv shell
    #   run: devenv shell hello
    #
